<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="itext7.pdfcalligraph" Version="5.0.1" />
    <PackageReference Include="itext7.pdfhtml" Version="6.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Selenium.WebDriver" Version="4.26.1" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="130.0.6723.9100" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MasterErp.Interface\RetailStation.Interface.csproj" />
  </ItemGroup>

</Project>
