export interface EmployeeSalaryModel {
    salaryId: number | null;
    employeeId: number;
    employeeCode: number;
    employeeName: string;
    branchId: number;
    executionDate: string;
    requestDate: string;
    isPaid: boolean | null;
    isGossi: boolean | null;
    basicSalary: number | null;
    extraSalary: number | null;
    workNature: number | null;
    transportation: number | null;
    housingAllowance: number | null;
    mobileAllowance: number | null;
    mealAllowance: number | null;
    overTime: number | null;
    other: number | null;
    other2: number | null;
    grossSalary: number | null;
    differenceDays: number | null;
    differenceCosteDays: number | null;
    totalGrossSalary: number | null;
    absence: number | null;
    penalty: number | null;
    loan: number | null;
    sickCost: number | null;
    transportDeduct: number | null;
    homeDeduct: number | null;
    otherDeduct: number | null;
    totalDeduct: number | null;
    netSalary: number | null;
    hRManagerApprove: boolean | null;
    financeManagerApprove: boolean | null;
    auditingApprove: boolean | null;
    executiveManagerApprove: boolean | null;
    generalManagerApprove: boolean | null;
    visaPayment: number | null;
    cashPayment: number | null;
    totalSalary: number | null;
}